apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-dictionary-deployment
spec:
  selector:
    matchLabels:
      app: pokemon-dictionary
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemon-dictionary
    spec:
      containers:
        - name: pokemon-dictionary
          image: reireias/pokemon-dictionary:arm
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: pokemon-dictionary
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-dictionary-service
spec:
  selector:
    app: pokemon-dictionary
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
