name: validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm .github/workflows/validate.yml
      - uses: instrumenta/kubeval-action@master
